version: '3'
services:

    cv:
        build: ./cv
        image: paskal/jsonresume
        command: export --theme kendall /tmp/gulyaeva.html

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public/cv/:/tmp/
            - ./cv/resume.json:/data/resume.json:ro

    pdf:
        image: pink33n/html-to-pdf
        command: --url https://ksinia.net/cv/gulyaeva.html --pdf gulyaeva.pdf
        privileged: true

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public/cv:/tmp/html-to-pdf
