version: '2'
services:

    build:
        image: paskal/jsonresume
        command: export --theme kendall-ksenia /tmp/resume_output/gulyaeva.html
        volumes:
            - ./public/cv/:/tmp/resume_output/
            - ./cv/resume.json:/data/resume.json:ro

    serve:
        image: paskal/jsonresume
        working_dir: /data/node_modules/jsonresume-theme-kendall-ksenia
        command: serve
        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"
        volumes:
            - ./cv/resume.json:/data/node_modules/jsonresume-theme-kendall-ksenia/resume.json:ro
        ports:
          - "4000:4000"

    build-pdf:
        image: pink33n/html-to-pdf
        command: --url https://ksinia.net/cv/gulyaeva.html --pdf gulyaeva.pdf
        privileged: true
        volumes:
            - ./public/cv:/workspace
