version: '2'
services:

    build:
        image: paskal/jsonresume
        entrypoint:
        - /bin/sh
        - -c
        - |
         resume export --theme $${THEME} /tmp/resume_output/gulyaeva.html && \
         sed -i 's/Work Experience/Experience/' /tmp/resume_output/gulyaeva.html
        environment:
          - THEME=kendall
        volumes:
            - ./public/cv/:/tmp/resume_output/
            - ./cv/resume.json:/data/resume.json:ro

    serve:
        image: paskal/jsonresume
        command: serve --theme=kendall
        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"
        volumes:
            - ./cv/resume.json:/data/resume.json:ro
        ports:
          - "4000:4000"

    build-pdf:
        image: pink33n/html-to-pdf
        command: --url https://ksinia.net/cv/gulyaeva.html --pdf gulyaeva.pdf
        privileged: true
        volumes:
            - ./public/cv:/tmp/html-to-pdf
