version: '2'
services:

    build:
        build: ./cv
        image: paskal/jsonresume
        entrypoint:
        - /bin/sh
        - -c
        - |
         resume export --theme $${THEME} /tmp/resume_output/gulyaeva.html && \
         sed -i 's/"Helvetica Neue", Helvetica/Calibri,Candara,Segoe,Segoe UI,Optima/' /tmp/resume_output/gulyaeva.html && \
         sed -i 's/<div class=\"bar\"><\/div>//' /tmp/resume_output/gulyaeva.html && \
         sed -i 's/13px/15px/' /tmp/resume_output/gulyaeva.html
        environment:
          - THEME=spartan

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public/cv/:/tmp/resume_output/
            - ./cv/resume.json:/data/resume.json:ro

    build-pdf:
        image: pink33n/html-to-pdf
        command: --url https://ksinia.net/cv/gulyaeva.html --pdf gulyaeva.pdf
        privileged: true

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public/cv:/tmp/html-to-pdf
