name: build

on:
  push:
    branches:
      - master
    tags:
    paths:
      - "resume.json"
  pull_request:
    paths:
      - "resume.json"

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - name: remote push to ksinia.net/cv/ from master
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl -s https://hooks.terrty.net/update/ksinia-cv/${UPDATER_KEY}
