name: build

on:
  push:
    branches:
      - master
    tags:
    paths:
      - "resume.json"

jobs:
  build-images:
    name: Rebuild resume
    runs-on: ubuntu-latest

    steps:
      - name: remote push to ksinia.net/cv/ from master
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl -s https://hooks.terrty.net/update/ksinia-cv/${UPDATER_KEY}
